name: Release

on: [push]

env: 
  TEST_ENV: ${{ secrets.TEST_ENV }}

# jobs:
#   release:
#     name: Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout branch
#         uses: actions/checkout@v2
#       - name: Generate Changelog
#         run: npx release-it --ci

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Print test
        run: echo "${{ TEST_ENV }}"
